const data = {

        "plants": [
          {"in_list": "false", "category" : "plant", "id": "1", "name": "AGLAONEMA BEAUTY", "detail": "Beautiful Aglaonema plant.", "image": "https://png.pngtree.com/png-clipart/20230529/original/pngtree-potted-aglaonema-plant-png-image_9173471.png"},
          {"in_list": "false", "category" : "plant", "id": "2", "name": "ALOCASIA GOLDEN", "detail": "Golden Alocasia plant.", "image": "https://webshop.plnts.com/media/catalog/product/cache/aa5d334f459227518b6c3cf7ea9d29ed/p/l/pl.s.bg.030-thumbnail_1.jpg" },
          {"in_list": "false", "category" : "plant", "id": "3", "name": "ANAR", "detail": "Pomegranate plant.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQekwhUVDfhxQvr6bB0WpZoFdTbHHc4Xk_bHwWgGA4lll9HxN21Sk9i4S-8td-sN-qbIVU&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "4", "name": "ANJEER", "detail": "Fig plant.", "image": "https://www.lilplants.com/wp-content/uploads/2017/08/Anjeer-Common-fig-Plant-1-600x600.jpg" },
          {"in_list": "false", "category" : "plant", "id": "5", "name": "APPLE", "detail": "Apple plant.", "image": "https://plantparadise.in/cdn/shop/products/WhatsAppImage2020-11-04at9.47.03AM_d27db6f7-adda-4a0a-bf92-c867138d7656_800x.jpg?v=1691200226" },
          {"in_list": "false", "category" : "plant", "id": "6", "name": "ARECA PALM", "detail": "Areca Palm.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf9YBrBUBO4bbWnxV8rwJJV7eoRus3y3_Zcw&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "7", "name": "POINSETTIA", "detail": "Poinsettia in a decorative box.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZuPLSOKKf66Kilh1uPXeYPB5GBJpxGbg9rw&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "8", "name": "BRASSIA GOLDEN", "detail": "Golden Brassia plant.", "image": "https://www.setgreen.com/uploaded/products/eb-image-1617244166.png" },
          {"in_list": "false", "category" : "plant", "id": "9", "name": "CALLA LILY", "detail": "Calla Lily plant.", "image": "https://png.pngtree.com/png-clipart/20231020/original/pngtree-white-calla-lilies-png-image_13381384.png" },
          {"in_list": "false", "category" : "plant", "id": "10", "name": "CHAMAEDOREA PALM ", "detail": "Chamaedorea Palm, known as Good Luck Palm.", "image": "https://etongreenindia.com/wp-content/uploads/2021/09/camandora.jpg" },
          {"in_list": "false", "category" : "plant", "id": "11", "name": "CHRYSANTHEMUM (SHEVANTI)", "detail": "Chrysanthemum (Shevanti) plant.", "image": "https://planaplant.com/cdn/shop/products/Websiteproductsize_2_455de0fb-1ea9-4220-8f77-0398967ba77c_627x700.jpg?v=1646307772" },
          {"in_list": "false", "category" : "plant", "id": "12", "name": "CYPRESS GOLDEN", "detail": "Golden Cypress plant.", "image": "https://nurserylive.com/cdn/shop/products/nurserylive-plants-cupressus-golden-golden-monterey-cyprss-plant-16968892416140.jpg?v=1634217967" },
          {"in_list": "false", "category" : "plant", "id": "13", "name": "CYPRESS SILVER", "detail": "Silver Cypress plant.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQC16HZ5aAADsMK4ICe39qLNWU_PdsFsHnuA&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "14", "name": "DRACAENA COMPACT", "detail": "Compact Dracaena", "image": "https://www.ugaoo.com/cdn/shop/files/Top5_8c938109-1b06-40e3-9664-c4d2adb4b470.jpg?v=1695447738&width=1500" },
          {"in_list": "false", "category" : "plant", "id": "15", "name": "DRACAENA CORDYLINE ", "detail": "Dracaena Cordyline Mumba ", "image": "https://nurserylive.com/cdn/shop/products/nurserylive-plants-cordyline-plant-16968795783308.jpg?v=1634217341" },
          {"in_list": "false", "category" : "plant", "id": "16", "name": "DRACAENA DARASINGH", "detail": "Dracaena Darasingh plant.", "image": "https://www.plantsguru.com/image/cache/cactus/dracaena-massangeana-giganta-800x800.jpg" },
          {"in_list": "false", "category" : "plant", "id": "17", "name": "DRACAENA GREEN", "detail": "Green Dracaena plant.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOARNV4RkFyp7y3Gd8xT8rlKtrgKHCb2n20A&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "18", "name": "DRACAENA MAHATMA", "detail": "Mahatma Dracaena plant.", "image": "https://ultimagardening.com/wp-content/uploads/2021/10/05-Ultima-Gardening-Nursery-Shop-Money-Plant-Green-26.png" },
          {"in_list": "false", "category" : "plant", "id": "19", "name": "DRACAENA SANDERIANA", "detail": "Lucky Bamboo Gold", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrvLSriGRCFt_VsViLo7t4qMfj4Oh6p4_94Q&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "20", "name": "FERN GOLDEN HB", "detail": "Golden Fern plant.", "image": "https://nurserynature.com/1129-large_default/golden-fern-plant.jpg" },
          {"in_list": "false", "category" : "plant", "id": "21", "name": "FICUS BONSAI", "detail": "Bonsai Ficus plant.", "image": "https://www.plantropan.com/wp-content/uploads/2023/08/Ficus-Bonsai-%E2%80%93-Plant.jpg" },
          {"in_list": "false", "category" : "plant", "id": "23", "name": "FICUS MICROCURPA", "detail": "Ficus Microcurpa.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWcpUp2I8Q9e2aDZLRgPyj33ZGxIWQskRo-w&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "24", "name": "FICUS MICROCURPA CONE", "detail": "Ficus Microcurpa Cone plant.", "image": "https://plantsworld.ae/cdn/shop/products/Ficusmicrocarpanitidaconehead_1_52M.jpg?v=1656349387&width=600" },
          {"in_list": "false", "category" : "plant", "id": "25", "name": "FICUS MOCLAME", "detail": "Moclame Ficus plant.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWcpUp2I8Q9e2aDZLRgPyj33ZGxIWQskRo-w&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "26", "name": "FICUS PANDA", "detail": "Panda Ficus plant.", "image": "https://www.plantsguru.com/image/cache/catalog/Alocassia/pg-ficus-panda-800x800.JPG" },
          {"in_list": "false", "category" : "plant", "id": "27", "name": "HIBISCUS AMERICAN DWARF", "detail": "Dwarf American Hibiscus plant.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1Lugpep_rZyZFnZp1Mn8G-zXQN2pAsaiftg&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "28", "name": "IMPATIENS (BALSAM)", "detail": "Impatiens (Balsam) plant.", "image": "https://5.imimg.com/data5/SELLER/Default/2023/10/350109207/AJ/NG/KG/17052731/2-500x500.jpg" },
          {"in_list": "false", "category" : "plant", "id": "29", "name": "JACOBINA", "detail": "Jacobina plant.", "image": "https://thegreenstack.store/cdn/shop/products/PhotoRoom-20230319_132831_1_grande.jpg?v=1679311578" },
          {"in_list": "false", "category" : "plant", "id": "30", "name": "JADE PLANT BONSAI BONZI", "detail": "Bonsai Bonsi Jade Plant.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL5cUuwgGy3BkHkr2Og0XbPszOE-Fo8qqonQ&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "31", "name": "JASMIN (MOGRA)", "detail": "Mogra Jasmine plant", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHgALvDtWoqwqJMTiBy6yEMB_2fQurHVsCSg&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "32", "name": "KALANCHOE", "detail": "Kalanchoe plant.", "image": "https://www.juneflowers.com/wp-content/uploads/2022/08/Kalanchoe-Plant.jpg" },
          {"in_list": "false", "category" : "plant", "id": "33", "name": "LOROPETLUM", "detail": "Loropetlum plant.", "image": "https://www.plantsguru.com/image/cache/New%20Plants/pg-loropetallum-chinesis-800x800.png" },
          {"in_list": "false", "category" : "plant", "id": "34", "name": "MADHUMALTI DORF (Jhumka Bel)", "detail": "Dorf Madhumalti plant.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCib_kcpyHEENUKqG9kpXN7Lor2Ayx5yExrw&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "35", "name": "MERRY", "detail": "Merry plant.", "image": "https://m.media-amazon.com/images/I/517OsYWqVML.jpg" },

          {"in_list": "false", "category" : "plant", "id": "36", "name": "METRO SIDIUS", "detail": "Metro Sidius plant.", "image": "" },

          {"in_list": "false", "category" : "plant", "id": "37", "name": "MONEY PLANT BIG LEAF SILVER", "detail": "Silver Money Plant with big leaves.", "image": "https://m.media-amazon.com/images/I/61x2Uwp55gL._AC_UF1000,1000_QL80_.jpg" },
          {"in_list": "false", "category" : "plant", "id": "38", "name": "MONEY PLANT GOLD KING", "detail": "Gold King Money Plant.", "image": "https://m.media-amazon.com/images/I/61RoMt3mQUL.jpg" },
          {"in_list": "false", "category" : "plant", "id": "39", "name": "MONEY PLANT GOLDEN (NEON)", "detail": "Golden Neon Money Plant.", "image": "https://elysianflora.com/wp-content/uploads/2021/12/moneygolden_45_1.png" },
          {"in_list": "false", "category" : "plant", "id": "40", "name": "MONEY PLANT MARBLE QUEEN", "detail": "Marble Queen Money Plant.", "image": "https://www.nationbloom.com/products/money-plant-marble-queen-plant-by-nationbloom.jpg" },
          {"in_list": "false", "category" : "plant", "id": "41", "name": "MONEY PLANT 'N' JOY", "detail": "'N' Joy Money Plant.", "image": "https://exoticflora.in/cdn/shop/products/moneyplantnjoy.jpg?v=1600339756" },
          {"in_list": "false", "category" : "plant", "id": "42", "name": "MORPANKHI GOLDEN", "detail": "Golden Morpankhi (Thuja)", "image": "https://www.plantsguru.com/image/cache/catalog/Asparagus/pg-morpankhi-800x800.jpg" },
          {"in_list": "false", "category" : "plant", "id": "43", "name": "ORCHID", "detail": "Orchid plant.", "image": "https://wildroots.in/wp-content/uploads/2023/07/orchid1.jpg" },
          {"in_list": "false", "category" : "plant", "id": "44", "name": "OXIPODIUM MOSTIC", "detail": "Oxipodium Cordatum Brazil Golden Mostic plant.", "image": "https://m.media-amazon.com/images/I/41U1+K6lb+L._AC_UF1000,1000_QL80_.jpg" },
          {"in_list": "false", "category" : "plant", "id": "45", "name": "PHILODENDRON BIRKIN", "detail": "Birkin Philodendron plant.", "image": "https://nestreeo.com/wp-content/uploads/2021/02/Philodendron-Birkin-Plant-2.jpg" },
          {"in_list": "false", "category" : "plant", "id": "46", "name": "PHILODENDRON BLACK", "detail": "Black Philodendron plant.", "image": "https://jiffyplants.com/wp-content/uploads/2022/01/ezgif.com-gif-maker-26.webp" },
          {"in_list": "false", "category" : "plant", "id": "47", "name": "PHYLANTHUS AMRAS", "detail": "Amras Phylanthus plant.", "image": "https://nurserylive.com/cdn/shop/products/nurserylive-bhuiamla-phyllanthus-niruri-plant_512x512.jpg?v=1634214437" },
          {"in_list": "false", "category" : "plant", "id": "48", "name": "POINSETTIA LOVE U PINK", "detail": "Love U Pink Poinsettia plant.", "image": "https://dfwmnhok7ak0p.cloudfront.net/78391/V11109/C/1623423069000/1280.jpg" },
          {"in_list": "false", "category" : "plant", "id": "49", "name": "POINSETTIA RED", "detail": "Red Poinsettia plant.", "image": "https://peppyflora.com/wp-content/uploads/2021/04/Poinsettia-Red-3x4-Product-Peppyflora-01-d-Moz.jpg" },
          {"in_list": "false", "category" : "plant", "id": "50", "name": "RADERMACHERA", "detail": "Radermachera plant.", "image": "https://lalitenterprise.com/cdn/shop/products/35.png?v=1669025739&width=1445" },
          {"in_list": "false", "category" : "plant", "id": "51", "name": "RHOEO", "detail": "Rhoeo plant.", "image": "https://www.plantsguru.com/image/cache/foliage-plants/rhoeo-spathacea-800x800.jpg" },
          {"in_list": "false", "category" : "plant", "id": "52", "name": "ROSE", "detail": "Rose plant.", "image": "https://kadiyamnursery.com/cdn/shop/products/hybrid-red-rose-flower-plant-live-plant-variety-roses-1-live-plant-kadiyam-nursery-1_1200x1200.jpg?v=1662733139" },
          {"in_list": "false", "category" : "plant", "id": "53", "name": "ROSE CREEPER", "detail": "Rose Creeper plant.", "image": "https://admin.thegreenyard.in/uploads/product_images/571169626-Creper-Rose.jpg" },
          {"in_list": "false", "category" : "plant", "id": "54", "name": "ROSE KASHMIRI", "detail": "Kashmiri Rose.", "image": "https://unlimitedgreens.com/cdn/shop/products/Kashmiri-Rose-Top.webp?v=1676462233" },
          {"in_list": "false", "category" : "plant", "id": "55", "name": "ROSE STANDING", "detail": "Standing Rose plant.", "image": "https://m.media-amazon.com/images/I/619xUWE9WxL._AC_UF894,1000_QL80_.jpg" },
          {"in_list": "false", "category" : "plant", "id": "56", "name": "RUBBER PLANT BLACK", "detail": "Black Rubber Plant.", "image": "https://unbeleafable.ph/wp-content/uploads/2021/02/Black-Prince.png" },
          {"in_list": "false", "category" : "plant", "id": "57", "name": "SITAPHAL GOLDEN", "detail": "Golden Sitaphal (Custard Apple).", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMzXcR5U5_WWbLUt-eFNe9zE56hb6ihJ_57g&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "58", "name": "TECOMA BIY COLOR", "detail": "Bicolor Tecoma plant.", "image": "https://www.jiomart.com/images/product/original/rv2d8wacyx/garden-art-orange-new-tecoma-bicolor-natural-live-healthy-indoor-air-purifier-plant-with-grower-pot-product-images-orv2d8wacyx-p600825206-3-202304222130.jpg?im=Resize=(420,420)" },
          {"in_list": "false", "category" : "plant", "id": "59", "name": "TECOMA ORANGE", "detail": "Orange Tecoma plant.", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRseT1jL7TUsw9w9L9ce-LYMWPpbo7Djkh8Zw&usqp=CAU" },
          {"in_list": "false", "category" : "plant", "id": "60", "name": "TECOMA PURPLE", "detail": "Purple Tecoma plant.", "image": "https://www.sindhuranursery.com/wp-content/uploads/2022/10/Tecoma-Purple-1.jpg" },
          {"in_list": "false", "category" : "plant", "id": "61", "name": "TECOMA YELLOW", "detail": "Yellow Tecoma plant.", "image": "https://m.media-amazon.com/images/I/61fFMb69JOL._AC_UF1000,1000_QL80_.jpg" },
          {"in_list": "false", "category" : "plant", "id": "62", "name": "ZAMIA BLACK", "detail": "Black Zamia (Raven) plant.", "image": "https://api.zamia.in/static/images/profile_image/23_i4PrYHA.jpg" },
          {"in_list": "false", "category" : "plant", "id": "63", "name": "ZAMIA GREEN", "detail": "Green Zamia plant.", "image": "https://5.imimg.com/data5/JC/GO/XP/SELLER-15983754/zamia-plant-500x500.jpg" },
          {"in_list": "false", "category" : "plant", "id": "64", "name": "ZAMIA ZENZI", "detail": "Zenzi Zamia plant.", "image": "https://rootbridges.com/cdn/shop/products/root-bridges-foliage-plants-5-pot-dwarf-zz-zenzi-plant-10923396890647_800x.jpg?v=1646547691" },
          {"in_list": "false", "category" : "plant", "id": "65", "name": "PEACE LILY", "detail": "Peace Lily (Spathyphyllum / Nagfani).", "image": "https://t4.ftcdn.net/jpg/00/40/90/99/360_F_40909915_l2cCc1mENVD85jbhTmAvswxpDpTdDAao.jpg" },
          {"in_list": "false", "category" : "plant", "id": "66", "name": "HOMALOMENA", "detail": "Homalomena plant.", "image": "https://airoguard.in/image/cache/catalog/Homalomena-rubescens-Maggy-Shield-Plant-13cm_5000x-550x550.jpg" },
          {"in_list": "false", "category" : "plant", "id": "67", "name": "JUNIPER GREEN", "detail": "Green Juniper plant.", "image": "https://www.plantsguru.com/image/cache/catalog/Asparagus/pg-juniper-pyramid-800x800.jpg" },
        ],

    "pots": [
      {"in_list": "false", 
      "id": "po_1", "category" : "pot", 
        "name": "Ceramic Pot",
        "image": "https://rukminim2.flixcart.com/image/850/1000/k0plpjk0/vase/y/n/h/00900-brightshop-original-imafkgdzysycetvc.jpeg?q=90",
        "detail": "Elegant ceramic pot to showcase your plants.",
      },
      {"in_list": "false", 
      "id": "po_2", "category" : "pot", 
        "name": "Terracotta Pot",
        "image": "https://media.istockphoto.com/id/153573626/photo/empty-flower-pot.jpg?s=612x612&w=0&k=20&c=WqwkrI_6Pp_ATAt6hAXgAZBxWRYoJRaEx7A9ewYwrDs=",
        "detail": "Classic terracotta pot for a rustic look.",
      }
    ],
    "manure": [
      {"in_list": "false", 
      "id": "m_1", "category" : "manure", 
        "name": "Organic Manure",
        "image": "/images/manure/organic-manure.jpg",
        "detail": "Nutrient-rich organic manure for healthy plants.",
      },
      {"in_list": "false", 
      "id": "m_2", "category" : "manure", 
        "name": "Compost",
        "image": "/images/manure/compost.jpg",
        "detail": "Natural compost to enrich your garden soil.",
      }
    ],
    "landscaping": [
      {"in_list": "na",
        "name": "Garden Designs",
        "id": "l_1", "category" : "landscaping", 
        "image": "https://lh3.googleusercontent.com/p/AF1QipM8xaM0zVMOtJlsB_RO-Oswtnv5YRbai3nusVDS=s680-w680-h510",
        "detail": "Professional garden design services for your home.",
      },
      {"in_list": "na",
        "name": "Home Designs",
        "id": "l_2", "category" : "landscaping", 
        "image": "https://lh3.googleusercontent.com/p/AF1QipMuEeTWqHF9WkxzUGMGX_ykBvl7bZ8uzvTbziJ2=s680-w680-h510",
        "detail": "Transform your office space with our landscaping expertise.",
      },
      {"in_list": "na",
        "name": "Office Designs",
        "id": "l_3", "category" : "landscaping", 
        "image": "https://lh3.googleusercontent.com/p/AF1QipP409CiyFAHZNs8gBZ5E5SBQ59RTDaGww7KGs1B=s680-w680-h510",
        "detail": "Transform your office space with our landscaping expertise.",
      },

    ]
  }

export default data;